### PR TITLE
fixed inconsistent blocking. fixed error messages

### PR DESCRIPTION
**Pull request by kalmasri123**

### CODE REVIEW

**Comment by kalmasri123** [comment]
To clarify: when clicking on a tweet, some users would remain unblocked despite either having an NFT pfp or being subscribed to twitter blue. I fixed the bug that was causing the loop to end early.

**Comment by Speedy2662** [comment]
LGTM! [https://i.imgur.com/gkh73n0.png](url)

**Comment by Speedy2662** [comment]
Hmm, after about 10-15 mins of going through some poopy cat tweets, it seems to have slowed down. It doesn't always log and doesn't seem to get all of the users. Worked great initially though, wonder what happened

**Comment by kalmasri123** [comment]
> Hmm, after about 10-15 mins of going through some poopy cat tweets, it seems to have slowed down. It doesn't always log and doesn't seem to get all of the users. Worked great initially though, wonder what happened
you might be getting rate limited? cant say for sure

**Comment by Speedy2662** [comment]
> you might be getting rate limited? cant say for sure

Few mins after I posted that, Twitter logged me out; after logging back in, it was working fine again!

**Comment by kalmasri123** [comment]
Closing this since there's another PR that supersedes it

**Pull request closed without merging**
