### PR TITLE
Add legacy-deps flag

### PR DESCRIPTION
**Pull request by rougetimelord**
Idk what happened? Check the action logs, but I think this fixes things??

### CODE REVIEW

**Comment by cooljeanius** [comment]
oh cool, let me try this in #328, too

**Comment by cooljeanius** [comment]
So, the full error output is:
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @crxjs/vite-plugin@1.0.14
npm error Found: vite@3.2.11
npm error node_modules/vite
npm error   dev vite@"^3.2.11" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^2.9.0" from @crxjs/vite-plugin@1.0.14
npm error node_modules/@crxjs/vite-plugin
npm error   dev @crxjs/vite-plugin@"^1.0.14" from the root project
npm error
npm error Conflicting peer dependency: vite@2.9.18
npm error node_modules/vite
npm error   peer vite@"^2.9.0" from @crxjs/vite-plugin@1.0.14
npm error   node_modules/@crxjs/vite-plugin
npm error     dev @crxjs/vite-plugin@"^1.0.14" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/2024-10-13T04_37_20_253Z-eresolve-report.txt

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-10-13T04_37_20_253Z-debug-0.log
```
idk, it sounds like it's implying that the `--legacy-peer-deps` is kind of a hack that's just meant to be a temporary workaround?

**Comment by cooljeanius** [comment]
...I mean, we can still try it if we can't fix the dependency resolution properly...

**Comment by rougetimelord** [comment]
> idk, it sounds like it's implying that the `--legacy-peer-deps` is kind of a hack that's just meant to be a temporary workaround?

Honestly I have no clue, I think it's just until the crxjs plugin gets updated to support vite 3.x?

**Comment by cooljeanius** [comment]
Hm, checking the @crxjs org page leads me to its docs: https://crxjs.dev/vite-plugin
...I'm still not really sure where to go from there, though...

**Pull request closed without merging**
