### PR TITLE
Document `jq` dependency in readme.md

### PR DESCRIPTION
**Pull request by cooljeanius**
See discussion in #327

### CODE REVIEW

**Comment by rougetimelord** [comment]
Is it possible to install jq in the makefile?

**Comment by cooljeanius** [comment]
> Is it possible to install jq in the makefile?

I mean, I guess, but that kinda seems like bad practice; generally makefiles aren't supposed to invoke the system package manager, since usually it's done the other way around. Also with so many system package managers out there, it'd be kind of a pain to handle all of them...

**Comment by smirkjuice** [comment]
> Also with so many system package managers out there, it'd be kind of a pain to handle all of them...

You could do 
`wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64` 
then run
`./jq-linux-amd64`,
 but I think it might need sudo to run the binary. You could also check the distro and use a package manager like this:
```shell
#!/bin/sh
. /etc/os-release
distro_name=$(echo $NAME)

if [$distro_name == "Fedora Linux"]; then
    sudo dnf install jq
elif [$distro_name == "Ubuntu"]; then
    sudo apt-get install jq
elif [$distro_name == "OpenSUSE Leap"]; then
    sudo zypper install jq
elif [$distro_name == "Arch Linux"]; then
    sudo pacman -S jq
fi
``` 
but that definitely needs sudo. I'm not sure how viable either of those options are for this though; I've never tried making browser extensions, never used Typescript, etc

**Comment by cooljeanius** [comment]
> > Also with so many system package managers out there, it'd be kind of a pain to handle all of them...
> 
> You could do `wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64` then run `./jq-linux-amd64`, but I think it might need sudo to run the binary. You could also check the distro and use a package manager like this:
> 
> ```shell
> #!/bin/sh
> . /etc/os-release
> distro_name=$(echo $NAME)
> 
> if [$distro_name == "Fedora Linux"]; then
>     sudo dnf install jq
> elif [$distro_name == "Ubuntu"]; then
>     sudo apt-get install jq
> elif [$distro_name == "OpenSUSE Leap"]; then
>     sudo zypper install jq
> elif [$distro_name == "Arch Linux"]; then
>     sudo pacman -S jq
> fi
> ```
> 
> but that definitely needs sudo. I'm not sure how viable either of those options are for this though; I've never tried making browser extensions, never used Typescript, etc

yeah this all seems like opening a huge can of worms; I think it'd be safer to just document the dependency instead of trying to auto-install it...

**Review by rougetimelord — APPROVED** [review]

**Pull request merged**
