### PR TITLE
Fix a small CSS syntax error

### PR DESCRIPTION
**Pull request by rougetimelord**
Popped out to me in the logs from #327 lol

### CODE REVIEW

**Review by cooljeanius — DISMISSED** [review]

**Review by cooljeanius — DISMISSED** [review]

**Comment by cooljeanius** [comment]
> The merge-base changed after approval.

OK so how does this keep reappearing immediately after I approve?

**Comment by rougetimelord** [comment]
Idk aaaaaaa

**Comment by rougetimelord** [comment]
There we go, shouldn't be fucky anymore :)

**Review by cooljeanius — APPROVED** [review]
ok, let's try this again...

**Pull request merged**
