### PR TITLE
0.4.3

### PR DESCRIPTION
**Pull request by rougetimelord**
Collecting a few PRs together that have all been assigned the same version string, so that it's less confusing!

Changes:
- Get users from like pages #286
- Use exponential backoff for internal messaging #285 
- Get users from hidden reply pages #305
- Rewrite EscapeHTML function to conform with OSWAP recommendations #295 
- Bump Firefox release workflow version
- Add privacy policy that is stored within the repo #296 
- Make tabs more granular, reduce built zip size #287 

Todo:
- [x]  Merge all PRs into version branch
- [x] Ensure `src/manifest.ts` and `package.json` have the correct version number
- [ ] Test locally
  - [ ] Chrome: `npm run build`
  - [ ] Firefox: `npm run build && make firefox`
- [ ] Squash and merge into main
- [ ] Create release for version

### CODE REVIEW

**Comment by cooljeanius** [comment]
I think we might want to make sure that the changes from browser-actions/release-firefox-addon#12 get included before merging this...

**Comment by cooljeanius** [comment]
> I think we might want to make sure that the changes from [browser-actions/release-firefox-addon#12](https://github.com/browser-actions/release-firefox-addon/pull/12) get included before merging this...

Also I wonder if we could get #296 in as well?

**Review by cooljeanius — DISMISSED** [review]
OK I bumped the version number for the Firefox release action; I'd say it's now good from my POV

**Comment by rougetimelord** [comment]
> > I think we might want to make sure that the changes from [browser-actions/release-firefox-addon#12](https://github.com/browser-actions/release-firefox-addon/pull/12) get included before merging this...
> 
> Also I wonder if we could get #296 in as well?

We should probably do that lol! I didn't bundle it in since #296 isn't a code change, but it should definitely get merged with (or before) we release this version

**Comment by rougetimelord** [comment]
Also @kheina, I'm pretty sure that the AMO external API doesn't have any endpoints to update a privacy policy :((( [the only endpoint I could find gets the privacy policy](https://mozilla.github.io/addons-server/topics/api/addons.html#addon-eula-policy)

We shouldn't need to update it, so I don't think it's super necessary to be able to automate that step. It also seems pretty common to not update the privacy policy on the addon page every time, and the privacy policy I wrote tells users that the version on the addon page may not be the most up to date.

I did open [an issue on the Mozilla addons repo about this too](https://github.com/mozilla/addons/issues/14927), so we will see.

**Review by cooljeanius — APPROVED** [review]

**Review by cooljeanius — DISMISSED** [review]
This is getting kinda big; let's try to save any further changes for a later release

**Comment by rougetimelord** [comment]
> This is getting kinda big; let's try to save any further changes for a later release

Yup that was the last thing lol

**Comment by rougetimelord** [comment]
> Mozilla says that they'll get an API method up and running in their 8/8 release :)) Then it should be as easy as adding a workflow to upload to AMO anytime the privacy policy file is touched.

PR merged! https://github.com/mozilla/addons-server/pull/22522

**Comment by cooljeanius** [comment]
> > Mozilla says that they'll get an API method up and running in their 8/8 release :)) Then it should be as easy as adding a workflow to upload to AMO anytime the privacy policy file is touched.
> 
> PR merged! [mozilla/addons-server#22522](https://github.com/mozilla/addons-server/pull/22522)

...well ok, would you like to get this into this release as well? Or would that be too much?

**Comment by kheina** [comment]
I'll do some work on this tonight and try to get it out. let's wait on the privacy policy stuff, that can go out without a release

**Review by kheina — DISMISSED** [review]
the code all looks good to me. I edited the privacy policy a little bit to make it sound a bit friendlier and a little clearer imo. I approved the PR and will update the privacy policy on AMO. @rougetimelord  feel free to merge if you think my changes to the privacy policy were ok https://github.com/kheina-com/Blue-Blocker/pull/312/commits/a3fb2c49f77c9cdc59e1e7db103d77784c6f782f

**Review by cooljeanius — APPROVED** [review]
I think the privacy policy changes are fine, but will wait for @rougetimelord for confirmation

**Review by cooljeanius — APPROVED** [review]

**Comment by cooljeanius** [comment]
@kheina I think you still need to re-approve, since #315 isn't merged yet...

**Review by kheina — APPROVED** [review]

**Comment by kheina** [comment]
> @kheina I think you still need to re-approve, since #315 isn't merged yet...

I didn't realize I could dismiss my own review

**Pull request merged**
