### PR TITLE
0.3.5

### LINKED ISSUE #219: Could not parse tweet: Tombstone
If the extension gets an API response with `type: TweetTombstone` the object gets passed to handleTweetObject which gracefully fails here:
https://github.com/kheina-com/Blue-Blocker/blob/d301118d32d5bef801c47df025dfd54857a95174/src/parsers/instructions.ts#L73

The TweetTombstone object looks like this:
```JSON
{
    "__typename": "TweetTombstone",
    "tombstone": {
        "__typename": "TextTombstone",
        "text": {
            "rtl": false,
            "text": "You’re unable to view this Post because this account owner limits who can view their Posts. Learn more",
            "entities": [
                {
                    "fromIndex": 92,
                    "toIndex": 102,
                    "ref": {
                        "type": "TimelineUrl",
                        "url": "https://help.twitter.com/rules-and-policies/notices-on-twitter",
                        "urlType": "ExternalUrl"
                    }
                }
            ]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by rougetimelord**
## Changelog
* Fix #219 which causes a spurious error event, by skipping tweet objects of type "TweetTombstone"
* Partially address #195 by checking for extended tweets

## Deployment Checklist
1. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
2. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
    - [ ] chrome should be tested with `npm run build`
    - [ ] test firefox locally using zip
3. [ ] merge into main
4. [ ] upload zips from `2` to chrome webstore and firefox addons

### CODE REVIEW

**Comment by rougetimelord** [comment]
Yo @cooljeanius and/or @kheina, for your review :)

**Review by cooljeanius — DISMISSED** [review]
LGTM, although I've only given it a quick look-over; haven't tested it at all...

**Comment by cooljeanius** [comment]
Before merging, though, I wonder if it'd be better to squash and merge, or to create a merge commit?

**Review by cooljeanius — DISMISSED** [review]

**Comment by kheina** [comment]
I think I decided that edit eligibility wasn't a good metric to determine if someone was a subscriber or not cause it showed regardless, so probably worth double checking that @cooljeanius 

also I normally squash and merge

**Comment by cooljeanius** [comment]
> I think I decided that edit eligibility wasn't a good metric to determine if someone was a subscriber or not cause it showed regardless, so probably worth double checking that @cooljeanius

hm, I would like to hear what @rougetimelord has to say...

**Comment by rougetimelord** [comment]
In my little bit of exploration the `edit_control` and `edit_control.is_edit_eligible` are always there, but `is_edit_eligible` is only set to true for accounts with premium. I haven't seen any false positives (i.e. non-premium user who doesn't have it set to true), but I have seen some false negatives.

**Comment by rougetimelord** [comment]
Ok more observations, for premium users `is_edit_eligible` seems to remain true even after `editable_until_msecs`. But it's true for tweets made by yourself until `editable_until_msecs`? And sometimes true for other non-premium accounts before then? But definitely false after for non-premium users. The behavior seems a bit bugged on Twitter's end

**Comment by cooljeanius** [comment]
> The behavior seems a bit bugged on Twitter's end

Hm, so do we wait for them to fix it, or just assume it won't ever get fixed?

**Comment by rougetimelord** [comment]
> Hm, so do we wait for them to fix it, or just assume it won't ever get fixed?

I'm guessing it won't be fixed/the behavior is correct but just looks weird (maybe it's set to true on self tweets to show the edit menu button to push you towards paying up?). I think the best choice is to add a check for self and/or check if `editable_until_msec` is in the past.

**Comment by cooljeanius** [comment]
> > Hm, so do we wait for them to fix it, or just assume it won't ever get fixed?
> 
> I'm guessing it won't be fixed/the behavior is correct but just looks weird (maybe it's set to true on self tweets to show the edit menu button to push you towards paying up?). I think the best choice is to add a check for self and/or check if `editable_until_msec` is in the past.
> 
> That should be enough to not cause false positives but it would increase the rate of false negatives further?

well ok, do you want to give it a try and test?

**Comment by rougetimelord** [comment]
Oof ok I'm abandoning trying to use the edit_control stuff to detect premium. I found a case where the timestamp was in the past and the eligibility was true on a non-premium user, so I'm flummoxed... Going to revert that but leave in the check for expandable tweets since that doesn't have the same problem.

**Comment by cooljeanius** [comment]
> Oof ok I'm abandoning trying to use the edit_control stuff to detect premium. I found a case where the timestamp was in the past and the eligibility was true on a non-premium user, so I'm flummoxed... Going to revert that but leave in the check for expandable tweets since that doesn't have the same problem.

What's the current status on this?

**Comment by rougetimelord** [comment]
> What's the current status on this?
Whoops!! I did some messy reverting but the branch is currently there

**Comment by cooljeanius** [comment]
> > What's the current status on this?
> 
> Whoops!! I did some messy reverting but the branch is currently there

"there" as in ready for review/squash-merging?

**Comment by rougetimelord** [comment]
Yup!

**Review by cooljeanius — APPROVED** [review]

**Pull request merged**
