### PR TITLE
v0.3.0 Long-Lived Branch (Rebased off v0.2.6 main)

### PR DESCRIPTION
**Pull request by jaredkotoff**
This is a long-lived branch, intended to aggregate all changes planned for version `0.3.0` (rebased off main to grab changes that were missed and fix conflicts)

Pull requests should be made against this branch

## Changelog
- rework repository to use typescript

## Deployment Checklist
1. [ ] merge all pull requests to llb
2. [ ] ensure manifests have the correct version/platform info (`manifest.json` points to chrome, `firefox-manifest.json` points to firefox)
3. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
    - [ ] test chrome locally using folder
    - [ ] test firefox locally using zip
4. [ ] merge llb to main
5. [ ] upload zips from `3` to chrome webstore and firefox addons

### CODE REVIEW

**Comment by MrAwesome** [comment]
Testing this locally, it doesn't seem to queue up any blocks at all in tweet/profile/search context - is that expected at this stage? (FF on Linux.)

(also, small note - had some confusion when building: there's still a manifest.json in the project root, and then the docs refer to `blue-blocker/build` so I spent a bit of time trying to figure out where the `blue-blocker` dir was. So we can probably just make that `build/`, or `Blue-Blocker/build`)

**Review by MrAwesome — APPROVED** [review]
Ope, never mind. "Pause user collection" was checked when I loaded it up. Doi. Looks good at a glance, going to rubberstamp it unless you need a closer review since this is just a rebase.

**Comment by MrAwesome** [comment]
Just noticed the search bugfix isn't in this - happy to port that over once this is in if you don't get to it

**Comment by DanielleMiu** [comment]
I'll try to test this out tomorrow. I have a dr appointment but hopefully I'll have time afterwards. also hoping the dr apt helps with all the shit I've been going through

**Comment by DanielleMiu** [comment]
so, immediate thoughts: I think the readme needs more info around dev, especially how you need to build via npm before running make firefox. it should also be noted somewhere you need to run `npm install` this is obvious for people like us, but I want this as idiot-friendly as possible, so having as much detail as possible is nice. if it's not concise enough maybe we can break it into it's own contributing file or something?

I also see the version is `1.0.0` again instead of `0.3.0`. I think all the old js files are still in the root of the dir, but that's easy to clean up

I'm running it now and will probably have more notes

**Comment by DanielleMiu** [comment]
a lot of the js in the popup seems to not be working
popup timer is not saved and has no value shown (nor "saved" indicator)
skip follower count no longer hides the threshold input when unchecked, and the input does not change the threshold value in the count. it doesn't look like it's saved either

at least on linux systems, the makefile zip preserves the original structure so you get a zip containing `build/`, `LICENSE`, and `readme.md`. zipping build directly fixes most of it, but the queue page doesn't seem to exist in the expected location. actually not sure this page is built at all. not sure how it works on chrome yet. I'm sure it's just some weirdness with the rebase or missing some stuff from 0.2.6

**Comment by DanielleMiu** [comment]
TODO
---

TS fixes
- [ ] firefox makefile (add new vite command for build firefox?)
- [ ] context menu styling
- [ ] context menu functionality (saving settings and hiding unnecessary options)
- [ ] extension pages missing

0.2.6 migration
- [ ] threshold and popup timer options
- [ ] block/unblock changes (fetch, additional headers, api url construction, etc)
- [ ] manifest permissions
- [ ] `https?` in request regex
- [ ] status in blue-blocker-event from inject.js
- [ ] greyscale icon on pause
- [ ] queue page (everything in pages folder, really)
- [ ] removing headers from parsers and universal headers (set headers function)
- [ ] context menu wording and styling
- [ ] formatlegacyname and abbreviate changes in utils

**Comment by DanielleMiu** [comment]
superceded by https://github.com/kheina-com/Blue-Blocker/pull/143

**Pull request closed without merging**
