### PR TITLE
Comprehensive blocking option

### PR DESCRIPTION
**Pull request by GaiZhenbiao**
Chinese and Vietnamese bots are everywhere, this option enables user to only block blue verified bots that uses none-ASCII characters in their names or uses any Vietnamese accent characters.

Don't block blue users:
image

Block none-ASCII blue users:
image

Settings panel:
image

Bots example:
image

### CODE REVIEW

**Comment by cooljeanius** [comment]
First thing I'd note is that there's no "e" in "non-ASCII"... beyond that, I'm not sure how I feel about this... the ability to block based off of certain characters in a display name has been requested before (#114, for instance), but this PR appears to be checking tweet bodies, too, which I think might be taking things too far...

**Comment by GaiZhenbiao** [comment]
Thanks for pointing out that typo! Checking tweet bodies is an optional setting, too.
image

Now I want to make a comprehensive blocking system for BlueBlocker, this is what it might looks like:
image

**Comment by rougetimelord** [comment]
I think that blocking users based if they are Vietnamese or use non-ASCII characters in their display name and/or tweets raises serious concerns about false positives and creates a risk of blocking non-bot users based on the language that they speak. Additionally, the example that you provided would already be blocked by the extension due to being verified by Premium membership.

**Comment by cooljeanius** [comment]
> I think that blocking users based on if they are Vietnamese or use non-ASCII characters in their display name and/or tweets raises serious concerns about false positives and creates a risk of blocking non-bot users based on the language that they speak. Additionally, the example that you provided would already be blocked by the extension due to being verified by Premium membership.

Yeah, plus there are merge conflicts now.

**Pull request closed without merging**
