### PR TITLE
create a new CI workflow, and update some of the existing ones

### PR DESCRIPTION
**Pull request by cooljeanius**
I'm thinking this add-on could use a little more testing.

### CODE REVIEW

**Comment by cooljeanius** [comment]
ok I give up for now; maybe I'll come back to it later...

**Comment by cooljeanius** [comment]
@rougetimelord @kheina any ideas as to how to get this to work?

**Comment by cooljeanius** [comment]
gah, merge conflicts in `package-lock.json` are the worst...

**Comment by cooljeanius** [comment]
Current failure is:
```
rendering chunks...
[crx:content-script-resources] Error: vite manifest is missing
    at Object.renderCrxManifest (file:///home/runner/work/Blue-Blocker/Blue-Blocker/node_modules/@crxjs/vite-plugin/dist/index.mjs:3240:21)
    at Object.generateBundle (file:///home/runner/work/Blue-Blocker/Blue-Blocker/node_modules/@crxjs/vite-plugin/dist/index.mjs:2922:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bundle.generate (file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:19017:9)
    at async file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:21688:27
    at async catchUnfinishedHookActions (file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:21076:16)
    at async build (file:///home/runner/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65392:16)
    at async CAC.<anonymous> (file:///home/runner/.config/yarn/global/node_modules/vite/dist/node/cli.js:828:5)
x Build failed in 401ms
error during build:
[crx:manifest-post] Error in crx:content-script-resources.renderCrxManifest
    at Object.generateBundle (file:///home/runner/work/Blue-Blocker/Blue-Blocker/node_modules/@crxjs/vite-plugin/dist/index.mjs:2933:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bundle.generate (file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:19017:9)
    at async file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:21688:27
    at async catchUnfinishedHookActions (file:///home/runner/.config/yarn/global/node_modules/rollup/dist/es/shared/node-entry.js:21076:16)
    at async build (file:///home/runner/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65392:16)
    at async CAC.<anonymous> (file:///home/runner/.config/yarn/global/node_modules/vite/dist/node/cli.js:828:5)
cat: build/manifest.json: No such file or directory
makefile:9: *** Extension version mismatch. manifest: , package.json: "0.4.10".  Stop.
Error: Process completed with exit code 2.
```

**Comment by rougetimelord** [comment]
ez cheesy

**Review by rougetimelord — APPROVED** [review]
CI passes, need CI anyways lol

**Review by rougetimelord — APPROVED** [review]
Might need to split this specifically off into it's own PR???

**Comment by cooljeanius** [comment]
> Might need to split this specifically off into it's own PR???

Possibly? idk
`¯\_(ツ)_/¯`

**Comment by rougetimelord** [comment]
> > Might need to split this specifically off into it's own PR???
> 
> Possibly? idk `¯\_(ツ)_/¯`

Made the PR, if it doesn't work idk what to do lol

**Comment by cooljeanius** [comment]
> > > Might need to split this specifically off into it's own PR???
> > 
> > 
> > Possibly? idk `¯\_(ツ)_/¯`
> 
> Made the PR, if it doesn't work idk what to do lol

ok cool, it seems to have worked

**Pull request merged**
