### PR TITLE
Switch Firefox Workflow Action

### PR DESCRIPTION
**Pull request by kheina**
switches from [publish-firefox-add-on](https://github.com/marketplace/actions/publish-firefox-add-on) to [release-firefox-addon](https://github.com/marketplace/actions/release-firefox-addon) which should support all of the different inputs we need.

Modified the release to support the new version (along with downloading the release source code from github using cURL (god I hope that github actions has curl installed by default))

whoever approves this PLEASE check all of the input types I use against those defined in the action: https://github.com/marketplace/actions/release-firefox-addon#inputs

### CODE REVIEW

**Comment by kheina** [comment]
this should be merged into #267 before it goes to main

**Comment by cooljeanius** [comment]
`actionlint` says:
```
$ actionlint
.github/workflows/release.yml:33:0: could not parse as YAML: yaml: line 33: did not find expected key [syntax-check]
   |
33 |         echo "sourcefile=$SOURCE_FILENAME" >> "$GITHUB_OUTPUT"
   | 
```

**Comment by kheina** [comment]
> `actionlint` says:
> 
> ```
> $ actionlint
> .github/workflows/release.yml:33:0: could not parse as YAML: yaml: line 33: did not find expected key [syntax-check]
>    |
> 33 |         echo "sourcefile=$SOURCE_FILENAME" >> "$GITHUB_OUTPUT"
>    | 
> ```

that's weird. looking into it but no idea what the issue there might be

**Comment by kheina** [comment]
@cooljeanius ok that should fix it

**Review by rougetimelord — APPROVED** [review]
Field types and names match the action documentation

**Comment by kheina** [comment]
> Field types and names match the action documentation

you should be good to cut a new release once 0.4.2 is merged, now. I think

**Comment by cooljeanius** [comment]
OK, so that fixed the previous parsing error; now there are some new ones from `shellcheck`, though:
```
$ actionlint
.github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2155:warning:1:8: Declare and assign separately to avoid masking return values [shellcheck]
   |
30 |       run: |
   |       ^~~~
.github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2086:info:2:109: Double quote to prevent globbing and word splitting [shellcheck]
   |
30 |       run: |
   |       ^~~~
```
(if we don't really care about these, it should be ok to just ignore them, I just think it's worthwhile to be explicit about being intentional about ignoring them)

**Comment by kheina** [comment]
> OK, so that fixed the previous parsing error; now there are some new ones from `shellcheck`, though:
> 
> ```
> $ actionlint
> .github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2155:warning:1:8: Declare and assign separately to avoid masking return values [shellcheck]
>    |
> 30 |       run: |
>    |       ^~~~
> .github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2086:info:2:109: Double quote to prevent globbing and word splitting [shellcheck]
>    |
> 30 |       run: |
>    |       ^~~~
> ```
> 
> (if we don't really care about these, it should be ok to just ignore them, I just think it's worthwhile to be explicit about being intentional about ignoring them)

ok tbh yeah that's not a bad idea

**Comment by kheina** [comment]
> OK, so that fixed the previous parsing error; now there are some new ones from `shellcheck`, though:
> 
> ```
> $ actionlint
> .github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2155:warning:1:8: Declare and assign separately to avoid masking return values [shellcheck]
>    |
> 30 |       run: |
>    |       ^~~~
> .github/workflows/release.yml:30:7: shellcheck reported issue in this script: SC2086:info:2:109: Double quote to prevent globbing and word splitting [shellcheck]
>    |
> 30 |       run: |
>    |       ^~~~
> ```
> 
> (if we don't really care about these, it should be ok to just ignore them, I just think it's worthwhile to be explicit about being intentional about ignoring them)

I just pushed it directly to the llb

**Pull request merged**
